sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install 4.2.2
  - nvm use 4.2.2
  - npm --version
  - node --version
  - npm install -g grunt-cli
install:
  - npm install phantomjs
  - npm install caniuse-db
  - npm install
script:
  - npm test