sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install 8.9
  - npm install -g grunt-cli
install:
  - npm run clean
  - php src/lib/pre-install.php --non-interactive
script:
  - npm run build
